environment:
  windows:
    path:
      - 'c:\node'
    userDefined:
      -
        key: 'te'
        value: 'et'
directory:
  -
    isDirectory: false
    fileName: 'test.txt'
    source: './SetupFileDirectory/test.txt'
    target: './TargetTest'
  -
    isDirectory: true
    fileName: ''
    source: './SetupFileDirectory/TestDir'
    target: './TargetTest'
    